// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToLibrary(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddToLibrary'](arg1, arg2, arg3, arg4);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDetailedConfig() {
  return window['go']['main']['App']['GetDetailedConfig']();
}

export function GetGameDetail(arg1) {
  return window['go']['main']['App']['GetGameDetail'](arg1);
}

export function GetLibrary() {
  return window['go']['main']['App']['GetLibrary']();
}

export function GetTaskStatus() {
  return window['go']['main']['App']['GetTaskStatus']();
}

export function RemoveFromLibrary(arg1) {
  return window['go']['main']['App']['RemoveFromLibrary'](arg1);
}

export function ResetConfig() {
  return window['go']['main']['App']['ResetConfig']();
}

export function SearchStore(arg1) {
  return window['go']['main']['App']['SearchStore'](arg1);
}

export function StartUnlock(arg1) {
  return window['go']['main']['App']['StartUnlock'](arg1);
}

export function TestProxy(arg1) {
  return window['go']['main']['App']['TestProxy'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function VerifyKey(arg1) {
  return window['go']['main']['App']['VerifyKey'](arg1);
}
